name: tdnizer_flutter
description: Tdnizer translate Tdn word to Japanese.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_core: ^1.2.1
  cloud_firestore: ^2.2.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
